import { useState } from 'react';
import { RiMore2Fill, RiStarLine, RiCheckboxCircleLine, RiCloseCircleLine, RiPlayCircleLine } from '@remixicon/react';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';

const toneBySeverity = { Crítica: 'critical', Alta: 'warning', Média: 'info', Baixa: 'neutral' } as const;

export function EvidenceCard({ alert, onOpen }: { alert: { id: string; type: string; severity: string; plate: string; driver: string; speed: number; time: string; location: string; status: string; evidence: string }; onOpen?: () => void }) {
  const [selected, setSelected] = useState(false);
  const [favorite, setFavorite] = useState(false);
  return <article className="panel overflow-hidden transition hover:-translate-y-0.5 hover:shadow-[0_12px_30px_rgba(16,24,40,.09)]"><button onClick={onOpen} className="video-surface relative block aspect-[16/8] w-full text-left"><div className="absolute inset-0 z-10 bg-gradient-to-t from-black/65 via-transparent to-black/20" /><div className="absolute left-3 top-3 z-20 flex gap-2"><Badge tone={toneBySeverity[alert.severity as keyof typeof toneBySeverity] ?? 'neutral'}>{alert.severity}</Badge>{alert.status === 'Novo' && <Badge tone="primary">Novo</Badge>}</div><div className="absolute bottom-3 left-3 z-20 text-white"><div className="text-xs font-semibold">{alert.type}</div><div className="mt-1 text-[10px] text-white/75">{alert.time} • {alert.speed} km/h</div></div><RiPlayCircleLine className="absolute left-1/2 top-1/2 z-20 size-10 -translate-x-1/2 -translate-y-1/2 text-white/80" /></button><div className="p-4"><div className="flex items-start justify-between gap-3"><div><button onClick={onOpen} className="text-sm font-semibold hover:text-[#335cff]">{alert.plate}</button><div className="mt-1 text-xs text-[#717784]">{alert.driver}</div></div><div className="flex"><Button size="icon" variant="ghost" onClick={() => setFavorite((value) => !value)} aria-label="Favoritar"><RiStarLine className={`size-4 ${favorite ? 'fill-[#d9850b] text-[#d9850b]' : ''}`} /></Button><Button size="icon" variant="ghost" aria-label="Mais ações"><RiMore2Fill className="size-4" /></Button></div></div><p className="mt-3 truncate text-[11px] text-[#8b92a0]">{alert.location}</p><div className="mt-3 flex items-center justify-between border-t border-[#eceef2] pt-3"><label className="flex items-center gap-2 text-[11px] font-medium text-[#626a78]"><input type="checkbox" checked={selected} onChange={(event) => setSelected(event.target.checked)} className="size-4 accent-[#335cff]" />Selecionar</label>{selected && <div className="flex"><Button size="icon" variant="ghost" className="text-[#dc3f4f]" aria-label="Rejeitar"><RiCloseCircleLine className="size-4" /></Button><Button size="icon" variant="ghost" className="text-[#1f9d62]" aria-label="Validar"><RiCheckboxCircleLine className="size-4" /></Button></div>}</div></div></article>;
}
