import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { RiAddLine, RiAlarmWarningLine, RiDeleteBinLine, RiLayoutGridLine, RiListCheck2, RiDownloadCloud2Line, RiCheckboxCircleLine, RiCloseCircleLine, RiTimeLine, RiMapPinLine, RiSpeedLine, RiRoadMapLine, RiMessage3Line } from '@remixicon/react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Field, Input, Select, Textarea } from '@/components/ui/Fields';
import { Checkbox } from '@/components/ui/SelectionControls';
import { FilterBar } from '@/components/ui/FilterBar';
import { Tabs } from '@/components/ui/Tabs';
import { Drawer, Modal } from '@/components/ui/Overlay';
import { VideoPanel, VideoMosaic } from '@/components/domain/VideoPanel';
import { MapCanvas } from '@/components/domain/MapCanvas';
import { EvidenceCard } from '@/components/domain/EvidenceCard';
import { ActivityTimeline } from '@/components/domain/ActivityTimeline';
import { DataTable } from '@/components/ui/DataTable';
import { alerts, evidence, vehicles } from '@/data/mock-data';

export function PlaybackDevicePage() {
  const [vehicle, setVehicle] = useState('');
  const [date, setDate] = useState('2026-09-23');
  const [loaded, setLoaded] = useState(false);
  return <>
    <PageHeader eyebrow="Centro de evidências" title="Reprodução de vídeo" description="Consulte gravações remotas por veículo, data e canal." actions={<Badge tone="info">Consulta simulada</Badge>} />
    <Card><div className="grid grid-cols-1 gap-3 border-b border-stroke-soft-200 p-4 md:grid-cols-[1fr_220px_auto]"><Field label="Selecionar veículo"><Select value={vehicle} onChange={(e) => { setVehicle(e.target.value); setLoaded(false); }}><option value="">Escolha um veículo</option>{vehicles.map((item) => <option key={item.id}>{item.plate} • {item.device}</option>)}</Select></Field><Field label="Data"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} disabled={!vehicle} /></Field><Button variant="primary" className="self-end" disabled={!vehicle || !date} onClick={() => setLoaded(true)}><RiDownloadCloud2Line className="size-4" /> Carregar gravações</Button></div><CardBody className="p-3">{loaded ? <div className="space-y-4"><VideoPanel title={`${vehicle} • Câmera frontal`} /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{['CH1 • Frontal', 'CH2 • Cabine', 'CH3 • Lateral', 'CH4 • Carga'].map((channel, index) => <button key={channel} className={`rounded-xl border p-3 text-left text-xs font-semibold ${index === 0 ? 'border-blue-300 bg-primary-lighter text-primary-darker' : 'border-stroke-soft-200 bg-bg-weak-25'}`}>{channel}<span className="mt-1 block text-[10px] font-normal text-text-soft-400">23 blocos disponíveis</span></button>)}</div></div> : <div className="flex min-h-[520px] flex-col items-center justify-center text-center"><div className="grid size-16 place-items-center rounded-2xl bg-primary-lighter text-primary-base"><RiDownloadCloud2Line className="size-8" /></div><h2 className="mt-5 text-base font-semibold">Selecione veículo e data</h2><p className="mt-2 max-w-md text-sm leading-6 text-text-sub-600">Os canais e a linha do tempo serão carregados aqui. Nenhum dispositivo real será consultado nesta versão visual.</p></div>}</CardBody></Card>
  </>;
}

export function VideoLibraryPage() {
  const [tab, setTab] = useState<'complete' | 'downloading' | 'waiting' | 'failed' | 'starred'>('complete');
  const [drawer, setDrawer] = useState(false);
  const rows = evidence.filter((item) => tab === 'complete' ? item.status === 'Completo' : tab === 'downloading' ? item.status === 'Baixando' : tab === 'waiting' ? item.status === 'Aguardando' : tab === 'failed' ? item.status === 'Falha' : Number(item.id.split('-')[1]) % 2 === 0);
  return <>
    <PageHeader eyebrow="Centro de evidências" title="Biblioteca de vídeo" description="Acompanhe solicitações, transferências e arquivos disponíveis." actions={<><Button disabled><RiDeleteBinLine className="size-4" /> Excluir</Button><Button variant="primary" onClick={() => setDrawer(true)}><RiAddLine className="size-4" /> Solicitar vídeo</Button></>} />
    <FilterBar resultCount={rows.length}><Field label="Placa"><Input placeholder="Buscar placa" /></Field><Field label="Frota"><Select><option>Todas as frotas</option><option>Operação Sudeste</option></Select></Field><Field label="Origem"><Select><option>Todas</option><option>Gravação</option><option>Caixa-preta</option></Select></Field><Field label="Período"><Input type="date" defaultValue="2026-09-23" /></Field></FilterBar>
    <Card><div className="flex flex-col justify-between gap-3 border-b border-stroke-soft-200 p-4 lg:flex-row lg:items-center"><Tabs items={[{ value: 'complete', label: 'Completo', count: 6 }, { value: 'downloading', label: 'Baixando', count: 2 }, { value: 'waiting', label: 'Aguardando', count: 1 }, { value: 'failed', label: 'Falha', count: 1 }, { value: 'starred', label: 'Com estrela', count: 3 }]} value={tab} onChange={setTab} /><div className="flex gap-1"><Button size="icon" variant="soft" aria-label="Grade"><RiLayoutGridLine className="size-4" /></Button><Button size="icon" variant="ghost" aria-label="Lista"><RiListCheck2 className="size-4" /></Button></div></div><DataTable data={rows} rowKey="id" selectable emptyTitle={`Nenhum item em ${tab}`} columns={[{ key: 'event', header: 'Evento', sortable: true, render: (r) => <span className="font-semibold text-text-strong-950">{r.event}</span> }, { key: 'plate', header: 'Placa', sortable: true, render: (r) => <span className="font-semibold text-primary-base">{r.plate}</span> }, { key: 'size', header: 'Tamanho' }, { key: 'duration', header: 'Duração' }, { key: 'time', header: 'Horário' }, { key: 'location', header: 'Local', width: '240px' }, { key: 'status', header: 'Status', render: (r) => <div className="min-w-28"><Badge tone={r.status === 'Completo' ? 'success' : r.status === 'Falha' ? 'critical' : r.status === 'Baixando' ? 'primary' : 'warning'}>{r.status}</Badge>{r.status === 'Baixando' && <div className="mt-2 h-1 overflow-hidden rounded-full bg-bg-soft-200"><div className="h-full bg-primary-base" style={{ width: `${r.progress}%` }} /></div>}</div> }]} /></Card>
    <Drawer open={drawer} onOpenChange={setDrawer} title="Solicitação de importação de vídeo" description="Configure uma tarefa local simulada" footer={<><Button onClick={() => setDrawer(false)}>Cancelar</Button><Button variant="primary" onClick={() => setDrawer(false)}>Criar solicitação</Button></>}>
      <div className="space-y-4"><Field label="Veículos"><Select multiple className="min-h-28">{vehicles.slice(0,6).map((vehicle) => <option key={vehicle.id}>{vehicle.plate} • {vehicle.device}</option>)}</Select></Field><div className="grid grid-cols-2 gap-3"><Field label="Início"><Input type="datetime-local" defaultValue="2026-09-23T08:30" /></Field><Field label="Duração"><Select><option>30 segundos</option><option>1 minuto</option><option>5 minutos</option></Select></Field></div><Field label="Nome da solicitação"><Input placeholder="Ex.: Evento 23 set manhã" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Fonte"><Select><option>Gravação</option><option>Caixa-preta</option></Select></Field><Field label="Tipo"><Select><option>Vídeo</option><option>Imagem</option></Select></Field></div><Field label="Canais"><div className="grid grid-cols-2 gap-2">{['CH1 • ADAS', 'CH2 • Cabine', 'CH3 • DSM', 'CH4 • Carga'].map((item) => <Checkbox key={item} defaultChecked className="rounded-10 border border-stroke-soft-200 p-3" label={item} />)}</div></Field><div className="grid grid-cols-2 gap-3"><Field label="Rede"><Select><option>Wi-Fi</option><option>Com fio</option><option>3G/4G/5G</option></Select></Field><Field label="Velocidade"><Select><option>Baixa</option><option>Alta</option></Select></Field></div><div className="rounded-xl border border-warning-light bg-warning-lighter p-3 text-xs leading-5 text-warning-dark">Velocidade alta pode interromper temporariamente a gravação local do equipamento.</div></div>
    </Drawer>
  </>;
}

export function AlertListPage() {
  const navigate = useNavigate();
  const [tab, setTab] = useState<'alerts' | 'favorites'>('alerts');
  const [view, setView] = useState<'grid' | 'list'>('grid');
  const [action, setAction] = useState<string | null>(null);
  const rows = useMemo(() => tab === 'alerts' ? alerts : alerts.filter((_, index) => index % 3 === 0), [tab]);
  return <>
    <PageHeader eyebrow="Centro de evidências" title="Lista de alertas" description="Revise, valide e distribua eventos com rastreabilidade." actions={<Button variant="primary" onClick={() => setAction('Validação de eventos')}><RiCheckboxCircleLine className="size-4" /> Validar seleção</Button>} />
    <FilterBar resultCount={rows.length}><Field label="Placa"><Input placeholder="Placa" /></Field><Field label="Motorista"><Input placeholder="Motorista" /></Field><Field label="Evento"><Select><option>Todos os eventos</option><option>Saída de pista</option><option>Distância insegura</option></Select></Field><Field label="Severidade"><Select><option>Todas</option><option>Crítica</option><option>Alta</option><option>Média</option></Select></Field><Field label="Status"><Select><option>Todos</option><option>Novo</option><option>Em análise</option><option>Resolvido</option></Select></Field><Field label="Evidência"><Select><option>Todos</option><option>Disponível</option><option>Processando</option><option>Sem vídeo</option></Select></Field><Field label="Data inicial"><Input type="date" defaultValue="2026-09-22" /></Field><Field label="Data final"><Input type="date" defaultValue="2026-09-23" /></Field></FilterBar>
    <Card><div className="flex flex-col justify-between gap-3 border-b border-stroke-soft-200 p-4 sm:flex-row sm:items-center"><Tabs items={[{ value: 'alerts', label: 'Alertas', count: alerts.length }, { value: 'favorites', label: 'Favoritos', count: 4 }]} value={tab} onChange={setTab} /><div className="flex gap-1"><Button size="icon" variant={view === 'grid' ? 'soft' : 'ghost'} onClick={() => setView('grid')} aria-label="Visualização em grade"><RiLayoutGridLine className="size-4" /></Button><Button size="icon" variant={view === 'list' ? 'soft' : 'ghost'} onClick={() => setView('list')} aria-label="Visualização em lista"><RiListCheck2 className="size-4" /></Button></div></div><CardBody>{view === 'grid' ? <div className="grid grid-cols-1 gap-4 md:grid-cols-2 2xl:grid-cols-3">{rows.map((alert) => <EvidenceCard key={alert.id} alert={alert} onOpen={() => navigate(`/ftv/ft/new-alarm-detail/${alert.id}`)} />)}</div> : <DataTable data={rows} rowKey="id" selectable onRowClick={(row) => navigate(`/ftv/ft/new-alarm-detail/${row.id}`)} columns={[{ key: 'type', header: 'Evento', render: (r) => <span className="font-semibold">{r.type}</span> }, { key: 'plate', header: 'Placa', sortable: true }, { key: 'driver', header: 'Motorista' }, { key: 'severity', header: 'Severidade', render: (r) => <Badge tone={r.severity === 'Crítica' ? 'critical' : r.severity === 'Alta' ? 'warning' : 'info'}>{r.severity}</Badge> }, { key: 'speed', header: 'Velocidade', render: (r) => `${r.speed} km/h` }, { key: 'status', header: 'Status' }, { key: 'evidence', header: 'Evidência' }, { key: 'time', header: 'Ocorrido em' }]} />}</CardBody></Card>
    <Modal open={action !== null} onOpenChange={(open) => !open && setAction(null)} title={action ?? 'Ação'} description="Fluxo visual sem alteração externa" footer={<><Button onClick={() => setAction(null)}>Cancelar</Button><Button variant="primary" onClick={() => setAction(null)}>Confirmar simulação</Button></>}><div className="space-y-4"><Field label="Resultado"><Select><option>Evento confirmado</option><option>Falso positivo</option><option>Requer nova análise</option></Select></Field><Field label="Observação"><Input placeholder="Registre o motivo da decisão" /></Field></div></Modal>
  </>;
}

export function AlarmDetailPage() {
  const { id = 'EVT-240921' } = useParams();
  const alert = alerts.find((item) => item.id === id) ?? alerts[0];
  const [tab, setTab] = useState<'summary' | 'history' | 'access'>('summary');
  const [decision, setDecision] = useState<string | null>(null);
  return <>
    <PageHeader back eyebrow={`Alertas / ${alert.id}`} title={alert.type} description={`${alert.plate} • ${alert.driver} • ${alert.time}`} actions={<><Button variant="danger" onClick={() => setDecision('Rejeitar evento')}><RiCloseCircleLine className="size-4" /> Rejeitar</Button><Button variant="primary" onClick={() => setDecision('Validar evento')}><RiCheckboxCircleLine className="size-4" /> Validar</Button></>} />
    <div className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6">{[[RiSpeedLine,'Velocidade',`${alert.speed} km/h`],[RiRoadMapLine,'Direção','Esquerda'],[RiMapPinLine,'Local',alert.location],[RiTimeLine,'Ocorrido em',alert.time]].map(([Icon,label,value]: any) => <Card key={label} className={label === 'Local' ? 'col-span-2' : ''}><div className="flex items-center gap-3 p-4"><div className="grid size-9 place-items-center rounded-xl bg-bg-weak-50 text-text-sub-600"><Icon className="size-4" /></div><div className="min-w-0"><div className="text-[10px] text-text-soft-400">{label}</div><div className="mt-1 truncate text-xs font-semibold">{value}</div></div></div></Card>)}</div>
    <div className="grid grid-cols-1 gap-4 2xl:grid-cols-[minmax(0,1.5fr)_420px]">
      <div className="space-y-4"><div className="grid grid-cols-1 gap-4 xl:grid-cols-2"><VideoPanel title={`${alert.plate} • ADAS frontal`} /><MapCanvas route compact selectedPlate={alert.plate} /></div><Card><CardHeader title="Evidências sincronizadas" description="Janela de 5 minutos antes e depois do evento" /><CardBody><VideoMosaic /></CardBody></Card></div>
      <Card className="h-fit"><div className="border-b border-stroke-soft-200 p-4"><Tabs items={[{ value: 'summary', label: 'Resumo' }, { value: 'history', label: 'Processamento' }, { value: 'access', label: 'Acessos' }]} value={tab} onChange={setTab} /></div><CardBody>{tab === 'summary' ? <><div className="rounded-xl border border-error-light bg-error-lighter p-4"><div className="flex items-center gap-2 text-sm font-semibold text-error-dark"><RiAlarmWarningLine className="size-5" />Recomendação de segurança</div><p className="mt-2 text-xs leading-5 text-error-dark">Revisar condução e orientar manutenção de distância segura antes do próximo turno.</p></div><dl className="mt-5 grid grid-cols-2 gap-4">{[['Condição','Saída contínua da faixa'],['Coordenadas','−23.5489, −46.6388'],['Status','Em análise'],['Evidência','4 canais disponíveis']].map(([label,value]) => <div key={label}><dt className="text-[10px] font-bold uppercase tracking-wide text-text-soft-400">{label}</dt><dd className="mt-1 text-xs font-semibold">{value}</dd></div>)}</dl><div className="mt-5 border-t border-stroke-soft-200 pt-5"><h3 className="mb-3 text-xs font-semibold">Colaboração</h3><div className="rounded-xl border border-stroke-soft-200 p-3"><Textarea className="min-h-20" placeholder="Adicionar comentário..." /><div className="flex justify-end"><Button size="sm" variant="primary"><RiMessage3Line className="size-4" /> Comentar</Button></div></div></div></> : <ActivityTimeline />}</CardBody></Card>
    </div>
    <Modal open={decision !== null} onOpenChange={(open) => !open && setDecision(null)} title={decision ?? 'Decisão'} description="A decisão ficará registrada na trilha de auditoria visual." footer={<><Button onClick={() => setDecision(null)}>Cancelar</Button><Button variant={decision?.startsWith('Rejeitar') ? 'danger' : 'primary'} onClick={() => setDecision(null)}>Confirmar</Button></>}><Field label="Justificativa"><Input placeholder="Descreva a decisão" /></Field></Modal>
  </>;
}
