/* eslint-disable @typescript-eslint/no-unused-vars -- index is reserved for future staggered card animation */
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { RiAddLine, RiArrowRightLine, RiCameraLine, RiCarLine, RiDeleteBinLine, RiDownload2Line, RiEditLine, RiFileUploadLine, RiInformationLine, RiMapPinLine, RiMore2Fill, RiRefreshLine, RiSignalTowerLine, RiUserSearchLine } from '@remixicon/react';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import { Field, Input, Select, Textarea } from '@/components/ui/Fields';
import { FilterBar } from '@/components/ui/FilterBar';
import { Modal } from '@/components/ui/Overlay';
import { PageHeader } from '@/components/ui/PageHeader';
import { Tabs } from '@/components/ui/Tabs';
import { VideoPanel } from '@/components/domain/VideoPanel';
import { drivers, fleets, vehicles } from '@/data/mock-data';

const unknownDrivers = [
  { id: 'face-1', plate: 'RQX6A36', date: 'Hoje, 08:36', confidence: '87%', status: 'Pendente' },
  { id: 'face-2', plate: 'FVT2D18', date: 'Hoje, 07:52', confidence: '81%', status: 'Pendente' },
  { id: 'face-3', plate: 'JLM8E44', date: 'Ontem, 17:31', confidence: '92%', status: 'Identificado' },
  { id: 'face-4', plate: 'TRC7L10', date: 'Ontem, 15:18', confidence: '74%', status: 'Descartado' },
];

function FormActions({ onSave }: { onSave?: () => void }) {
  const navigate = useNavigate();
  return <div className="mt-6 flex justify-end gap-2 border-t border-stroke-soft-200 pt-5"><Button onClick={() => navigate(-1)}>Cancelar</Button><Button variant="primary" onClick={onSave}>Salvar cadastro</Button></div>;
}

export function UnknownDriverPage() {
  const [tab, setTab] = useState<'pending' | 'resolved'>('pending');
  const [modal, setModal] = useState(false);
  return <>
    <PageHeader eyebrow="FT Vision • Segurança" title="Motoristas não identificados" description="Revise capturas de cabine e vincule cada rosto a um motorista cadastrado." actions={<Button><RiRefreshLine className="size-4" /> Atualizar capturas</Button>} />
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><Tabs value={tab} onChange={setTab} items={[{ value: 'pending', label: 'Pendentes', count: 2 }, { value: 'resolved', label: 'Tratados', count: 2 }]} /><div className="text-xs text-text-sub-600">Retenção visual: 30 dias</div></div>
    <FilterBar resultCount={tab === 'pending' ? 2 : 2}><Field label="Período"><Input type="date" defaultValue="2026-09-23" /></Field><Field label="Veículo"><Select><option>Todos os veículos</option>{vehicles.slice(0,5).map((item) => <option key={item.id}>{item.plate}</option>)}</Select></Field><Field label="Confiança mínima"><Select><option>Qualquer</option><option>Acima de 80%</option><option>Acima de 90%</option></Select></Field></FilterBar>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{unknownDrivers.filter((item) => tab === 'pending' ? item.status === 'Pendente' : item.status !== 'Pendente').map((item, index) => <Card key={item.id} className="overflow-hidden"><div className="relative grid aspect-[4/3] place-items-center driver-evidence-surface"><div className="absolute inset-4 rounded-xl border border-dashed border-static-white/55" /><RiUserSearchLine className="size-12 text-static-white/70" /><span className="absolute bottom-3 left-3 rounded-md bg-static-black/45 px-2 py-1 font-mono text-[9px] text-static-white">CABINE • CH2</span><Badge className="absolute right-3 top-3" tone={item.status === 'Pendente' ? 'warning' : item.status === 'Identificado' ? 'success' : 'neutral'}>{item.status}</Badge></div><CardBody><div className="flex items-start justify-between"><div><strong>{item.plate}</strong><p className="mt-1 text-[11px] text-text-sub-600">{item.date}</p></div><span className="text-xs font-bold text-primary-base">{item.confidence}</span></div><Button className="mt-4 w-full" variant={item.status === 'Pendente' ? 'primary' : 'secondary'} onClick={() => setModal(true)}>{item.status === 'Pendente' ? 'Identificar motorista' : 'Revisar tratamento'}<RiArrowRightLine className="size-4" /></Button></CardBody></Card>)}</div>
    <Modal open={modal} onOpenChange={setModal} title="Identificar motorista" description="A vinculação será registrada no histórico do evento." footer={<><Button onClick={() => setModal(false)}>Cancelar</Button><Button variant="primary" onClick={() => setModal(false)}>Confirmar vínculo</Button></>}><div className="space-y-4"><div className="rounded-xl border border-stroke-soft-200 bg-bg-weak-50 p-4 text-xs text-text-sub-600"><RiInformationLine className="mb-2 size-5 text-primary-base" />Compare a imagem da cabine com o cadastro antes de confirmar.</div><Field label="Motorista"><Select><option>Selecione um motorista</option>{drivers.map((item) => <option key={item.id}>{item.name}</option>)}</Select></Field><Field label="Observação"><Input placeholder="Motivo ou contexto do vínculo" /></Field></div></Modal>
  </>;
}

export function FleetPage() {
  const navigate = useNavigate();
  return <><PageHeader eyebrow="FT Vision • Administração" title="Gestão de frotas" description="Estruture unidades operacionais, grupos e permissões de acesso." actions={<><Button><RiDownload2Line className="size-4" /> Exportar</Button><Button variant="primary" onClick={() => navigate('/ftv/ft/fleet-manage/add-fleet')}><RiAddLine className="size-4" /> Nova frota</Button></>} /><FilterBar resultCount={fleets.length}><Field label="Frota"><Input placeholder="Nome, código ou ID externo" /></Field><Field label="UF"><Select><option>Todos os estados</option><option>SP</option><option>RS</option><option>GO</option></Select></Field></FilterBar><Card><DataTable data={fleets} rowKey="id" selectable columns={[
    { key: 'name', header: 'Nome da frota', sortable: true, render: (row) => <div><strong className="text-text-strong-950">{row.name}</strong><span className="block text-[10px] text-text-soft-400">{row.code}</span></div> }, { key: 'externalId', header: 'ID externo' }, { key: 'address', header: 'Localização', sortable: true }, { key: 'groups', header: 'Grupos' }, { key: 'vehicles', header: 'Veículos', sortable: true }, { key: 'updated', header: 'Atualização' }, { key: 'actions', header: '', render: () => <Button size="icon" variant="ghost" aria-label="Mais ações"><RiMore2Fill className="size-4" /></Button> },
  ]} /></Card></>;
}

export function AddFleetPage() {
  const navigate = useNavigate();
  return <><PageHeader back eyebrow="Gestão de frotas" title="Adicionar frota" description="Cadastre uma unidade operacional e defina seus dados de identificação." /><Card className="mx-auto max-w-4xl"><CardHeader title="Informações da frota" description="Campos marcados são necessários para organizar veículos e usuários." /><CardBody><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome da frota"><Input placeholder="Ex.: Operação Norte" /></Field><Field label="Código interno"><Input placeholder="Ex.: NT-05" /></Field><Field label="ID externo"><Input placeholder="Identificador no ERP" /></Field><Field label="Telefone da unidade"><Input placeholder="+55 (00) 00000-0000" /></Field><Field className="sm:col-span-2" label="Endereço"><Input placeholder="Rua, número e complemento" /></Field><Field label="Cidade"><Input placeholder="Cidade" /></Field><Field label="Estado"><Select><option>Selecione</option><option>São Paulo</option><option>Paraná</option><option>Bahia</option></Select></Field><Field className="sm:col-span-2" label="Descrição"><Textarea placeholder="Contexto operacional e observações" /></Field></div><FormActions onSave={() => navigate('/ftv/ft/fleet-manage')} /></CardBody></Card></>;
}

export function VehicleManagePage() {
  const navigate = useNavigate();
  const [transfer, setTransfer] = useState(false);
  return <><PageHeader eyebrow="FT Vision • Administração" title="Veículos e dispositivos" description="Gerencie associação de frota, hardware, sinal e canais de vídeo." actions={<><Button onClick={() => setTransfer(true)}>Transferir frota</Button><Button variant="primary"><RiAddLine className="size-4" /> Vincular veículo</Button></>} /><FilterBar resultCount={vehicles.length}><Field label="Veículo"><Input placeholder="Placa, dispositivo ou motorista" /></Field><Field label="Frota"><Select><option>Todas as frotas</option>{fleets.map((item) => <option key={item.id}>{item.name}</option>)}</Select></Field><Field label="Status"><Select><option>Todos</option><option>Em movimento</option><option>Parado</option><option>Offline</option></Select></Field><Field label="Modelo"><Select><option>Todos os modelos</option><option>ADPLUS 2.0</option><option>ADPLUS X</option></Select></Field></FilterBar><Card><DataTable data={vehicles} rowKey="id" selectable onRowClick={() => navigate('/ftv/ft/vehicle-manage/detail')} columns={[
    { key: 'plate', header: 'Placa', sortable: true, render: (row) => <strong className="text-text-strong-950">{row.plate}</strong> }, { key: 'device', header: 'Dispositivo', sortable: true }, { key: 'fleet', header: 'Frota', sortable: true }, { key: 'model', header: 'Modelo' }, { key: 'driver', header: 'Motorista' }, { key: 'status', header: 'Status', render: (row) => <Badge tone={row.status === 'Offline' ? 'neutral' : row.status === 'Em movimento' ? 'success' : 'warning'}>{row.status}</Badge> }, { key: 'signal', header: 'Sinal' }, { key: 'channels', header: 'Canais' },
  ]} /></Card><Modal open={transfer} onOpenChange={setTransfer} title="Transferir veículos" description="Selecione a frota de destino dos itens marcados." footer={<><Button onClick={() => setTransfer(false)}>Cancelar</Button><Button variant="primary" onClick={() => setTransfer(false)}>Confirmar transferência</Button></>}><Field label="Frota de destino"><Select><option>Selecione</option>{fleets.map((item) => <option key={item.id}>{item.name}</option>)}</Select></Field><p className="mt-4 text-xs text-text-sub-600">Permissões e regras de compartilhamento serão recalculadas após a transferência.</p></Modal></>;
}

export function VehicleDetailPage() {
  const [tab, setTab] = useState<'overview' | 'device' | 'channels'>('overview');
  const vehicle = vehicles[0];
  return <><PageHeader back eyebrow={`Veículos • ${vehicle.plate}`} title="Detalhes do veículo" description="Cadastro, dispositivo embarcado, conectividade e canais de vídeo." actions={<><Button><RiEditLine className="size-4" /> Editar</Button><Button variant="danger"><RiDeleteBinLine className="size-4" /> Desvincular</Button></>} /><div className="mb-4"><Tabs value={tab} onChange={setTab} items={[{ value: 'overview', label: 'Visão geral' }, { value: 'device', label: 'Dispositivo' }, { value: 'channels', label: 'Canais de vídeo', count: 4 }]} /></div><div className="grid gap-4 xl:grid-cols-[1fr_1.5fr]"><Card><CardHeader title="Identificação" description="Dados administrativos e operacionais" /><CardBody className="grid grid-cols-2 gap-4">{[['Placa',vehicle.plate],['Frota',vehicle.fleet],['Motorista',vehicle.driver],['Modelo','Mercedes-Benz Atego'],['Chassi','9BM958150NB•••••'],['Status',vehicle.status],['Última posição','Rod. Anhanguera, km 104'],['Atualização',vehicle.lastSeen]].map(([label,value]) => <div key={label}><div className="text-[10px] font-semibold uppercase tracking-wide text-text-soft-400">{label}</div><div className="mt-1 text-xs font-semibold">{value}</div></div>)}</CardBody></Card><Card><CardHeader title={tab === 'channels' ? 'Prévia dos canais' : 'Saúde do dispositivo'} description={tab === 'channels' ? 'Quadro mais recente recebido' : 'Leitura do terminal e periféricos'} /><CardBody>{tab === 'channels' ? <div className="grid grid-cols-2 gap-3">{[1,2,3,4].map((channel) => <div key={channel} className="rounded-xl bg-bg-strong-950 p-4 text-static-white"><RiCameraLine className="size-6 text-blue-300" /><div className="mt-8 text-xs font-semibold">Canal {channel}</div><div className="text-[10px] text-static-white/50">Online • 1080p</div></div>)}</div> : <div className="grid gap-3 sm:grid-cols-2">{[[RiSignalTowerLine,'Conectividade','4G • Excelente'],[RiCameraLine,'Câmeras','4 de 4 online'],[RiCarLine,'Ignição','Ligada'],[RiMapPinLine,'GPS','Precisão de 4 m']].map(([Icon,label,value]) => { const ItemIcon = Icon as typeof RiCameraLine; return <div key={String(label)} className="rounded-xl border border-stroke-soft-200 p-4"><ItemIcon className="size-5 text-primary-base" /><div className="mt-3 text-xs text-text-sub-600">{String(label)}</div><div className="mt-1 text-sm font-semibold">{String(value)}</div></div>; })}</div>}</CardBody></Card></div><Card className="mt-4"><CardHeader title="Transmissão de teste" description="Componente visual de conferência do canal frontal" /><CardBody><VideoPanel compact /></CardBody></Card></>;
}

export function DriverManagePage() {
  const navigate = useNavigate();
  const active = useMemo(() => drivers.filter((item) => item.status === 'Ativo').length, []);
  return <><PageHeader eyebrow="FT Vision • Administração" title="Motoristas" description={`${active} motoristas ativos com histórico de condução e reconhecimento facial.`} actions={<><Button><RiDownload2Line className="size-4" /> Exportar</Button><Button variant="primary" onClick={() => navigate('/ftv/ft/driver-manage/driver/add-driver')}><RiAddLine className="size-4" /> Novo motorista</Button></>} /><FilterBar resultCount={drivers.length}><Field label="Motorista"><Input placeholder="Nome ou CPF" /></Field><Field label="Frota"><Select><option>Todas as frotas</option>{fleets.map((item) => <option key={item.id}>{item.name}</option>)}</Select></Field><Field label="Status"><Select><option>Todos</option><option>Ativo</option><option>Inativo</option><option>Férias</option></Select></Field></FilterBar><Card><DataTable data={drivers} rowKey="id" selectable columns={[
    { key: 'name', header: 'Motorista', sortable: true, render: (row) => <div className="flex items-center gap-3"><div className="grid size-8 place-items-center rounded-full bg-primary-lighter font-bold text-primary-base">{row.name.split(' ').map((part) => part[0]).slice(0,2).join('')}</div><div><strong className="text-text-strong-950">{row.name}</strong><span className="block text-[10px] text-text-soft-400">{row.cpf}</span></div></div> }, { key: 'fleet', header: 'Frota', sortable: true }, { key: 'status', header: 'Status', render: (row) => <Badge tone={row.status === 'Ativo' ? 'success' : row.status === 'Férias' ? 'warning' : 'neutral'}>{row.status}</Badge> }, { key: 'score', header: 'Score', sortable: true, render: (row) => <strong className={row.score >= 94 ? 'text-success-dark' : 'text-warning-dark'}>{row.score}</strong> }, { key: 'distance', header: 'Distância' }, { key: 'events', header: 'Eventos' }, { key: 'updated', header: 'Atualização' },
  ]} /></Card></>;
}

export function AddDriverPage() {
  const navigate = useNavigate();
  const [photo, setPhoto] = useState(false);
  return <><PageHeader back eyebrow="Motoristas" title="Adicionar motorista" description="Cadastre os dados e uma referência facial para identificação automática." /><Card className="mx-auto max-w-5xl"><CardHeader title="Cadastro do motorista" description="A foto deve mostrar o rosto de frente, com boa iluminação." /><CardBody><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><button onClick={() => setPhoto(true)} className="flex aspect-square flex-col items-center justify-center rounded-2xl border-2 border-dashed border-stroke-sub-300 bg-bg-weak-25 text-text-sub-600 transition hover:border-blue-300 hover:bg-primary-lighter"><RiFileUploadLine className="size-8 text-primary-base" /><strong className="mt-3 text-xs">{photo ? 'Foto adicionada' : 'Enviar foto facial'}</strong><span className="mt-1 text-[10px]">JPG ou PNG • até 5 MB</span></button><div className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="Nome completo"><Input placeholder="Nome civil completo" /></Field><Field label="CPF"><Input placeholder="000.000.000-00" /></Field><Field label="Matrícula"><Input placeholder="Código do colaborador" /></Field><Field label="Telefone"><Input placeholder="+55 (00) 00000-0000" /></Field><Field label="E-mail"><Input type="email" placeholder="nome@empresa.com" /></Field><Field label="CNH"><Input placeholder="Número da habilitação" /></Field><Field label="Validade da CNH"><Input type="date" /></Field><Field className="sm:col-span-2" label="Frota principal"><Select><option>Selecione uma frota</option>{fleets.map((item) => <option key={item.id}>{item.name}</option>)}</Select></Field></div></div><FormActions onSave={() => navigate('/ftv/ft/driver-manage/driver')} /></CardBody></Card></>;
}
